### ISSUE TITLE
Translations are going too deep

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-translate-plugin#44]
When adding a key to the $translatable array:
```
$translatable = [
    'title', 'image', ...
];
```
I noticed that the translation is picking up **all** `title/image/...` **fields**
What I mean with this is that when you have the following structure (simplified it):
```
title:
    label: Title field
repeater:
    form:
        fields:
            data:
                type: nestedForm
                    form:
                        fields:
                            title:
                                label: Title field in repeater
```
The translation will pick up `[title]` but also `repeater[x][data][title]`.
Meaning `[title]` will always have the value of `repeater[lastIndex][data][title]`.
This also occurs with my image (which I posted about in Discord), which is why when removing `[image]` is not working because the translation is saving `repeater[lastIndex][data][image]` in my `[image]` field

I would expect it would only pick the `title/image` field located in `Plugin[image]` and that fields inside a jsonable field are ignored.

The workaround is to create unique keys. Instead of `title` in repeater, use `repeater_title`, ...
Note that `repeater[x][data][title]` is also getting the locale switcher thingy

![image](https://user-images.githubusercontent.com/89913092/192972580-03ac45d9-f3eb-47cc-a4a4-5c1c6ddec284.png)
Note how `RLTranslate` sets image on the `Blog[image]` but also on `Blog[blocks][0][data][image]`
![image](https://user-images.githubusercontent.com/89913092/192972467-459dccd6-f63a-496b-957e-833e576e0122.png)
